name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.x'
    - run: |
        system_profiler SPHardwareDataType SPSoftwareDataType SPSerialATADataType
    - run: |
        brew tap homebrew/cask-versions
        brew cask install safari-technology-preview
        sudo /Applications/Safari\ Technology\ Preview.app/Contents/MacOS/safaridriver --enable
        echo $?
        safaridriver --port 0 &
        pip3 install selenium
        echo start...
        python3 stp.py
