name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.x'
    - run: |
        system_profiler SPHardwareDataType SPSoftwareDataType SPSerialATADataType
        sudo sqlite3 /var/db/auth.db .dump | grep "safaridriver"
    - run: |
        echo "========== /etc/sudoers"
        sudo cat /etc/sudoers
        echo "========== /etc/sudoers.d"
        sudo ls -ltra /etc/sudoers.d
        #echo "========== new password"
        #sudo dscl . passwd /Users/$(whoami) "hogehoge"
    - run: |
        ## brew tap homebrew/cask-versions
        ## brew update
        ## brew cask install safari-technology-preview
        #"/Applications/Safari Technology Preview.app/Contents/MacOS/safaridriver" --version
        #echo "========== STP installed"
        #expect -c "
        #spawn \"/Applications/Safari Technology Preview.app/Contents/MacOS/safaridriver\" --enable
        #expect \"Password:\"
        #sleep 2
        #send \"hogehoge\n\"
        #interact
        #"
        ## sudo /Applications/Safari\ Technology\ Preview.app/Contents/MacOS/safaridriver --version
        ## sudo /Applications/Safari\ Technology\ Preview.app/Contents/MacOS/safaridriver --enable
        ## sudo /Applications/Safari\ Technology\ Preview.app/Contents/MacOS/safaridriver --port 0 &
        defaults write com.apple.Safari IncludeDevelopMenu YES
        defaults write com.apple.Safari AllowRemoteAutomation 1
        sudo safaridriver --enable
    - run: |
        # safaridriver --port 0 &
        mkdir screenshots
        pip3 install selenium
        echo "----- screenshots 1"
        screencapture screenshots/1.png
        echo $?
        ls -la screenshots
        pwd
        echo "----- start..."
        ## sudo python3 stp.py || echo stp
        sudo python3 s.py
        sudo find ./ -name "*.png"
    - uses: actions/upload-artifact@master
      with:
        name: screenshots
        path: screenshots/*.png
